name: Whiskers check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Whiskers
        uses: catppuccin/setup-whiskers@v2
        with:
          whiskers-version: 2.5.1

      - name: Check themes are updated
        run: |
          whiskers --check themes/ fleet.tera
